version: '3'

volumes:
  mongo_data: {}

services:
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    container_name: ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - "./ipfs0:/data/ipfs"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  api:
    container_name: api
    build:
      context: .
    depends_on:
      - mongodb
      - ipfs
    environment:
      MONGODB_URI: "mongodb://root:rootpassword@mongodb:27017"
      IPFS_URI: "/dns4/ipfs/tcp/5001"
    ports:
      - "8081:8081"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro